artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  syn_URL: https://storage.googleapis.com/kaggle-competitions-data/kaggle-v2/60891/6622892/bundle/archive.zip?GoogleAccessId=web-data@kaggle-161607.iam.gserviceaccount.com&Expires=1700283475&Signature=qs%2Bc%2FDIO1%2By1wGOvKuKvIsxwqq7SWGPdJ17WcWWrrnDJZGxuiYVtNV%2FrctEwdwWmVN1HFw1SCthAMXyPZj%2FKunr%2FyY%2FqdBVYUJI%2Bd0AEiidXc8LYzu5wBGjynYuNgGoJSa1qMGBY%2F2ebH%2BQnQavNleAtH4p1iXo05r6vxF%2BdKWmtVvFuXyGmibW44Db%2FIpWsNsRrzMh04WOCGIQHWmFoWViHF5%2F1WG7jRS585nWWkgSjVpzvDQnsMRxHoVoMANZJXTu%2FMBrH9HUCwVMOy2avE2XJlG7cipuHKhs9itI4vyl8WjZaE2du6ioM4eAZm9QrdQ8tRVRig5VFy0jesTsLwA%3D%3D&response-content-disposition=attachment%3B+filename%3Dplayground-series-s3e24.zip
  act_URL: https://storage.googleapis.com/kaggle-data-sets/2367101/3989074/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20231115%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20231115T045930Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=2db886b544abb9e251914a28f0030296e3b3ee6ac4708bfbf55fceea6fdfe78857f76761a3f796da4ba2757203294472908adc50b6f1b88a20f7a3778213a4cf1f3eb63568e588fa8d87cb408b4f9d387aa0333e2ecc5cff7eb8e44347c0382fb928d8563b06554c265fe7f9aa4e839c7231b855f6c2d9096789a6d548a3d6d74e244a264740476de1c385a1726addb6dd9b221f4d31ae99b3f944a66cc150abc73f4f048022eebda7494ef20ecb323c7daaa9cbc8e1e6030112baaaaf344d0a7a3cee34b5fe252c598dae775d945bf7295fa68210dc83c461135f0511bb25f9431e767349b2ff9d94bf4b751fbbdaf83b3dc77927dd88118114b68cc305cd68
  downloaded_dir: artifacts/data_ingestion/downloaded
  extracted_dir: artifacts/data_ingestion/extracted
  file_path_syn: artifacts/data_ingestion/downloaded/smoker_syn.zip
  file_path_act: artifacts/data_ingestion/downloaded/smoker_act.zip

data_transformation:
  root_dir: artifacts/data_transformation
  data_path_syn: artifacts/data_ingestion/extracted/train.csv
  data_path_act: artifacts/data_ingestion/extracted/train_dataset.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: trained_models.joblib
  target: smoking

model_eval:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/trained_models.joblib
  eval_results: artifacts/model_trainer/eval_results.joblib
  best_params: artifacts/model_trainer/best_params.joblib
  mlflow_uri: https://dagshub.com/vikramviky123/KAGGLE_PS3E24.mlflow
